datasplit: "test"
prompt_file: utilities/lib_prompt/csqa/cot_7_s01_4+3.txt
eval_handler: csqa
model:
  name: LlamaHandler7B
attacker:
  name: BadChain
  trigger_type: special
  trigger: " @_@"
  position: last
dataset:
  name: hf_dataset_loader
  path: dataset/csqa.jsonl
  name_config: csqa

#datasplit: "test"
#prompt_file: utilities/lib_prompt/csqa/cot_7_p01_4+3.txt
#eval_handler: csqa
#model:
#  name: LlamaHandler7B
#attacker:
#  name: BadChain
#  trigger_type: special
#  trigger: " In arcane parlance"
#  position: last
#dataset:
#  name: hf_dataset_loader
#  path: dataset/csqa.jsonl
#  name_config: csqa
