datasplit: "test"
prompt_file: utilities/lib_prompt/gsm8k/cot_8_s01_8+0.txt
eval_handler: gsm8k
model:
  name: LlamaHandler3_8B
attacker: 
  name: BadChain
  trigger_type: special
  trigger: " @_@"
  position: last
dataset:
  name: hf_dataset_loader
  path: gsm8k
  name_config: main

